# Generated by Django 5.2.7 on 2025-10-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='محصول',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('نام', models.CharField(max_length=100)),
                ('سایز', models.CharField(max_length=10)),
                ('رنگ', models.CharField(max_length=20)),
                ('قیمت', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='مشتری',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('نام', models.CharField(max_length=100)),
                ('تلفن', models.CharField(blank=True, max_length=15)),
                ('آدرس', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.CreateModel(
            name='سفارش',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('تعداد', models.IntegerField(default=1)),
                ('تاریخ_سفارش', models.DateTimeField(auto_now_add=True)),
                ('وضعیت', models.CharField(choices=[('در_انتظار', 'در انتظار'), ('تایید_شده', 'تایید شده'), ('ارسال_شده', 'ارسال شده')], default='در_انتظار', max_length=20)),
                ('کارتن', models.BooleanField(default=False, verbose_name='کارتنی')),
                ('صورت_مشتری', models.BooleanField(default=False, verbose_name='صورت مشتری')),
                ('محصول', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.محصول')),
                ('مشتری', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.مشتری')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
