# Generated by Django 5.2.7 on 2025-10-23 06:42

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_محصول_مشتری_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='سفارش',
            name='تعداد_کارتن',
            field=models.IntegerField(default=0, verbose_name='تعداد کارتن'),
        ),
        migrations.AddField(
            model_name='سفارش',
            name='جفت_در_کارتن',
            field=models.IntegerField(default=0, verbose_name='تعداد جفت در هر کارتن'),
        ),
        migrations.AddField(
            model_name='سفارش',
            name='یادداشت',
            field=models.TextField(blank=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='سفارش',
            name='تاریخ_سفارش',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش (شمسی)'),
        ),
        migrations.AlterField(
            model_name='سفارش',
            name='تعداد',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد (جفت)'),
        ),
        migrations.AlterField(
            model_name='سفارش',
            name='صورت_مشتری',
            field=models.BooleanField(default=False, verbose_name='صورت حساب مشتری'),
        ),
        migrations.AlterField(
            model_name='سفارش',
            name='محصول',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.محصول', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='سفارش',
            name='مشتری',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.مشتری', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='سفارش',
            name='وضعیت',
            field=models.CharField(choices=[('در_انتظار', '⏳ در انتظار'), ('تایید_شده', '✅ تایید شده'), ('در_حال_تولید', '🔧 در حال تولید'), ('آماده_ارسال', '📦 آماده ارسال'), ('ارسال_شده', '🚚 ارسال شده'), ('لغو_شده', '❌ لغو شده')], default='در_انتظار', max_length=20, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='سفارش',
            name='کارتن',
            field=models.BooleanField(default=False, verbose_name='سفارش کارتنی'),
        ),
        migrations.AlterField(
            model_name='محصول',
            name='قیمت',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
