# Generated by Django 5.2.7 on 2025-10-23 07:20

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_سفارش_تعداد_کارتن_سفارش_جفت_در_کارتن_سفارش_یادداشت_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس کامل')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('size', models.CharField(max_length=10, verbose_name='سایز')),
                ('color', models.CharField(max_length=20, verbose_name='رنگ')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)')),
                ('stock', models.IntegerField(default=0, verbose_name='موجودی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.RemoveField(
            model_name='سفارش',
            name='محصول',
        ),
        migrations.RemoveField(
            model_name='سفارش',
            name='مشتری',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('status', models.CharField(choices=[('pending', '⏳ در انتظار تایید'), ('confirmed', '✅ تایید شده'), ('production', '🔧 در حال تولید'), ('ready', '📦 آماده ارسال'), ('delivered', '🚚 ارسال شده'), ('cancelled', '❌ لغو شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('is_invoice', models.BooleanField(default=False, verbose_name='صورت حساب مشتری')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد (جفت)')),
                ('is_carton', models.BooleanField(default=False, verbose_name='سفارش کارتنی')),
                ('carton_count', models.IntegerField(default=0, verbose_name='تعداد کارتن')),
                ('pairs_per_carton', models.IntegerField(default=0, verbose_name='تعداد جفت در هر کارتن')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.DeleteModel(
            name='محصول',
        ),
        migrations.DeleteModel(
            name='سفارش',
        ),
        migrations.DeleteModel(
            name='مشتری',
        ),
    ]
